---
- name: Creates directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0755'
    force: false
  loop:
    - "{{ flame_home }}"
    - "{{ flame_data }}"

- name: Copy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0644'
    backup: true
  loop:
    - { src: '.env.j2', dest: '{{ flame_home }}/.env' }
    - { src: 'docker-compose.yml.j2', dest: '{{ flame_home }}/docker-compose.yml' }

- name: Restart flame
  ansible.builtin.shell: echo success
  notify:
    Restart flame
